# Generated by Django 4.2.3 on 2023-07-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=30)),
                ('professor_name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
